server:
  port: 8086
spring:
  datasource:
    url: jdbc:sqlite:game-library.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: true

# Удаляем или комментируем:
# jackson:
#   property-naming-strategy: SNAKE_CASE

logging:
  level:
    org.hibernate.SQL: DEBUG
