server:
  port: 8086

spring:
  datasource:
    url: jdbc:sqlite:game-library.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: INFO
    com.example.game_library: DEBUG
    org.hibernate.SQL: DEBUG
